# https://emanual.robotis.com/docs/en/dxl/mx/mx-64-2/

# https://stackoverflow.com/questions/62550215/parsing-yaml-file-using-yaml-cpp

# Protocol 1


# EEPROM
model_name: MX_64R    # !!!! The underscore instead of hyphen very important
operating_modes:
  - current_control: 0
    velocity_control: 1
    position_control: 3
    multiturn_control: 4
    current_based_position_control: 5
    PWM_control: 16 
motor_data: 
  - field: MODEL_NBR
    address: 0
    length: 2
    unit: 1
  - field: FIRMWARE
    address: 2
    length: 1
    unit: 1
  - field: ID
    address: 3
    length: 1
    unit: 1
  - field: BAUDRATE
    address: 4
    length: 1
    unit: 1
  - field: RETURN_DELAY
    address: 5
    length: 1
    unit: 0.000002
  - field: CW_ANGLE_LIMIT
    address: 6
    length: 2
    unit: 0.001536
  - field: CCW_ANGLE_LIMIT
    address: 8
    length: 1
    unit: 0.001536
  - field: TEMP_LIMIT
    address: 11
    length: 1
    unit: 1
  - field: MIN_VOLT_LIMIT
    address: 12
    length: 1
    unit: 0.1
  - field: MAX_VOLT_LIMIT
    address: 13
    length: 1
    unit: 0.1
  - field: MAX_TORQUE
    address: 14
    length: 2
    unit: 0.1
  - field: STATUS_RETURN
    address: 16
    length: 1
    unit: 1
  - field: ALARM_LED
    address: 17
    length: 1
    unit: 1
  - field: SHUTDOWN
    address: 18
    length: 1
    unit: 1
  - field: MULTITURN_OFFSET
    address: 20
    length: 2
    unit: 1
  - field: RES_DIVIDER
    address: 22
    length: 1
    unit: 1
  
  # RAM
  - field: TRQ_ENABLE
    address: 24
    length: 1
    unit: 1
  - field: LED
    address: 25
    length: 1
    unit: 1
  - field: D_GAIN
    address: 26
    length: 1
    unit: 1
  - field: I_GAIN
    address: 27
    length: 1
    unit: 1
  - field: P_GAIN
    address: 28
    length: 1
    unit: 1
  - field: GOAL_POS
    address: 30
    length: 2
    unit: 0.001536
  - field: MOVING_SPEED
    address: 32
    length: 2
    unit: 0.0119
  - field: TORQUE_LIMIT
    address: 34
    length: 2
    unit: 0.1
  - field: PRESENT_POS
    address: 36
    length: 2
    unit: 0.001536
  - field: PRESENT_SPEED
    address: 38
    length: 2
    unit: 0.0115
  - field: PRESENT_LOAD
    address: 40
    length: 2
    unit: 0.1
  - field: PRESENT_VOLT
    address: 42
    length: 1
    unit: 0.1
  - field: PRESENT_TEMP
    address: 43
    length: 1
    unit: 1
  - field: REGISTERED
    address: 44
    length: 1
    unit: 1
  - field: MOVING
    address: 46
    length: 1
    unit: 1
  - field: LOCK
    address: 47
    length: 1
    unit: 1
  - field: PUNCH
    address: 48
    length: 2
    unit: 1
  - field: REALTIME_TICK
    address: 50
    length: 2
    unit: 0.001
  - field: CURRENT
    address: 68
    length: 2
    unit: 0.0045
  - field: TRQ_MODE_ENABLE
    address: 70
    length: 1
    unit: 1
  - field: GOAL_TORQUE
    address: 71
    length: 2
    unit: 0.0045
  - field: GOAL_ACC
    address: 73
    length: 1
    unit: 0.0175


